export const GET_SALES_REQUEST = 'GET_SALES_REQUEST';
export const GET_SALES_SUCCESS = 'GET_SALES_SUCCESS';
export const GET_SALES_FAILURE = 'GET_SALES_FAILURE';

export const CREATE_SALES_REQUEST = 'CREATE_SALES_REQUEST';
export const CREATE_SALES_SUCCESS = 'CREATE_SALES_SUCCESS';
export const CREATE_SALES_FAILURE = 'CREATE_SALES_FAILURE';

export const EDIT_SALES_REQUEST = 'EDIT_SALES_REQUEST';
export const EDIT_SALES_SUCCESS = 'EDIT_SALES_SUCCESS';
export const EDIT_SALES_FAILURE = 'EDIT_SALES_FAILURE';

export const DELETE_SALES_REQUEST = 'DELETE_SALES_REQUEST';
export const DELETE_SALES_SUCCESS = 'DELETE_SALES_SUCCESS';
export const DELETE_SALES_FAILURE = 'DELETE_SALES_FAILURE';

export const GET_SALE_BY_ID_REQUEST = 'GET_SALE_BY_ID_REQUEST';
export const GET_SALE_BY_ID_SUCCESS = 'GET_SALE_BY_ID_SUCCESS';
export const GET_SALE_BY_ID_FAILURE = 'GET_SALE_BY_ID_FAILURE';
